version: '3'

services: 
  mysql:
    image: mysql:8.0.2
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: withme
    ports:
      - "3308:3306"
  
  client:
    image: mysql:8.0.2
    depends_on:
      - mysql
    command: mysql -uroot -proot -hmysql withme
  
  myadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"